### PR TITLE
Output TagInfo <script> tag

### PR DESCRIPTION
**Pull request by harry-wood**
For the "[taginfo taglists](https://wiki.openstreetmap.org/wiki/Taginfo/Taglists)" on the wiki. This thing is already in place and working, but so far we've kept a chunk of code on https://wiki.openstreetmap.org/wiki/MediaWiki:Common.js and @joto has been asking wiki admins (like me) to make little tweaks to it. He wanted to host it at his end instead (good idea?)

The approach for having mediawiki spit out a &lt;script> tag is [based on this answer](http://stackoverflow.com/a/26436873/338265). I have tested it. It works. But maybe you can see a better way.

### CODE REVIEW

**Comment by joto** [comment]
One thing: Should the link go to https? Or `//taginfo.openstreetmap.org` so it works with both http and https?

**Comment by harry-wood** [comment]
oh yeah. well spotted. Fixed

**Comment by tomhughes** [comment]
Can you not just use `mw.loader.load(<url>)` in the `Common.js` page?

**Comment by tomhughes** [comment]
See https://www.mediawiki.org/wiki/ResourceLoader/Modules#mediaWiki.loader and https://www.mediawiki.org/wiki/ResourceLoader/Legacy_JavaScript for more.

**Comment by harry-wood** [comment]
oh yeah that works. DONE! https://wiki.openstreetmap.org/w/index.php?title=MediaWiki%3ACommon.js&type=revision&diff=1368345&oldid=1342124

**Pull request closed without merging**
