### PR TITLE
Add mobile interface to wiki

### PR DESCRIPTION
**Pull request by MaxSem**
Uses the MobileFrontend extension. Done with Grant looking over my shoulder.

### CODE REVIEW

**Comment by Firefishy** [comment]
@tomhughes please would you mind merging when you have a chance.

**Comment by tomhughes** [comment]
Merged (with fixes) as d1aaa91efdb8ce6731d80943b9696d1538909f5f.

**Comment by MaxSem** [comment]
Err, requires Mantle, too. We got rid of this dependency later, but 1.24 is aeons ago by MW standards:P

**Comment by HolgerJeromin** [comment]
Thank you so much. Works perfect on opera mobile classic.

**Pull request closed without merging**
