### PR TITLE
Add new SSH key for Matt

### PR DESCRIPTION
**Pull request by zerebubuth**
Since #489, I should be using an SSH key to log in, but it looks like I didn't have one set up (oops).

### CODE REVIEW

**Comment by tomhughes** [comment]
Merged, but I have already fixed this mornings issue with the changeset feed by manually renaming the temporary state file over the main state file which was empty.

**Comment by zerebubuth** [comment]
Yes, I noticed the failure emails stopped. Thanks for that!

I was logging in to fix it when I noticed that I couldn't any more. :facepalm:

**Comment by Firefishy** [comment]
Sorry! I should have checked more extensively that everyone had good SSH keys.

**Comment by zerebubuth** [comment]
Haha, no worries. It's pretty indicative of how often I need to log in that it was almost 3 months before I made this PR :sweat_smile: (Actually, longer, since I didn't actually have to log in - Tom already fixed the problem I was getting alerts for!)

**Pull request merged**
