### PR TITLE
Create masmovil.rb

### PR DESCRIPTION
**Pull request by heroku-miraheze**

### CODE REVIEW

**Comment by tomhughes** [comment]
Sorry, can you explain what these PRs are about? If you're offering tile caches then you should contact us first and we would normally take care of configuring them...

**Comment by heroku-miraheze** [comment]
To offer MasMovil caches.

**Comment by tomhughes** [comment]
Well one of them looks like it is a render server?

But as I say you really need to contact operations@osmfoundation.org with details of what you are proposing to offer so we can discuss the specifications and make arrangements to provide you with our credentials or for you to provide us with login details.

**Comment by heroku-miraheze** [comment]
Push all commits now.

**Comment by Firefishy** [comment]
@heroku-miraheze Thank you for the pull requests. Please can you email us to discuss? operations@osmfoundation.org

Gracias por las "pull request". ¿Puede enviarnos un correo electrónico para discutir? operations@osmfoundation.org

**Pull request closed without merging**
