### PR TITLE
Block requests for tiles unless they come from a CDN node

### PR DESCRIPTION
**Pull request by tomhughes**
A first attempt at implementing https://github.com/openstreetmap/operations/issues/679.

Things it still needs:

* Allowing statuscake check ranges (do we have a source for these?)
* Allowing OSMF IP ranges (this would be a massive pain though we could do the main data centres easily)

### CODE REVIEW

**Comment by pnorman** [comment]
> * Allowing OSMF IP ranges (this would be a massive pain though we could do the main data centres easily)

I think Dublin and Amsterdam is enough.

**Comment by tomhughes** [comment]
I've added the statuscake IPs now.

**Comment by grischard** [comment]
What will be the error message for unauthorised IP addresses, 403?

**Comment by tomhughes** [comment]
I think so yes.

**Comment by Firefishy** [comment]
@pnorman @tomhughes Is this ready to go? Should we communicate anything out about this change?

**Comment by tomhughes** [comment]
I believe it is ready, yes.

**Review by pnorman — APPROVED** [review]

**Comment by pnorman** [comment]
I don't see any need for announcements. No one should be using our internal addresses

**Comment by tomhughes** [comment]
Sadly this doesn't work because the client IP has already been mapped to the real IP by the time the check is done. I was hoping that putting the IP check before we configured the mod_remoteip stuff would avoid that but it doesn't :-(

**Pull request merged**
