### PR TITLE
Add server location description to aws

### PR DESCRIPTION
**Pull request by gravitystorm**
I couldn't find anywhere more specific than just "Ireland" for the AWS datacentres.

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
https://aws.amazon.com/about-aws/global-infrastructure/?nc1=h_ls says something about Dublin for Ireland.

**Comment by gravitystorm** [comment]
@tomhughes This PR was closed but not merged - was there a problem?

**Comment by tomhughes** [comment]
Wasn't me!

**Comment by tomhughes** [comment]
Merged now anyway - no idea what the mirror script was doing.

**Pull request closed without merging**
