### PR TITLE
Test only: move long running jobs to the front

### PR DESCRIPTION
**Pull request by mmd-osm**
(test only, please ignore)

### CODE REVIEW

**Comment by tomhughes** [comment]
You don't need to pollute this repo with PRs just to do a test - you can just push to your own fork and the actions will run there.

**Comment by mmd-osm** [comment]
Yes, good point, will do.

**Comment by mmd-osm** [comment]
I will try to quickly explain what this was all about: minimizing overall runtime by ordering jobs by decreasing runtime.

In a first step I moved all slow jobs to a dedicated yml, so that the GitHub scheduler treats them as related group of jobs. Ideally this group gets scheduled as early as possible. 

Tests finished in 30 minutes (without error this time), woth `stateofthemap` and `wiki` taking the longest. Those two jobs probably need a bit more of an optimization.

I'm sure there some better and more deterministic way to control job scheduling. At least this small test has shown that there's some potential.

chef


`state of the map` spends pretty large amounts of time in bundle install --deployment.

```
Thu, 14 May 2020 18:05:18 GMT Recipe: stateofthemap::default
Thu, 14 May 2020 18:07:54 GMT   * execute[/srv/2016.stateofthemap.org/Gemfile] action run
Thu, 14 May 2020 18:07:54 GMT     - execute bundle install --deployment
Thu, 14 May 2020 18:10:29 GMT   * execute[/srv/2017.stateofthemap.org/Gemfile] action run
Thu, 14 May 2020 18:10:29 GMT     - execute bundle install --deployment
Thu, 14 May 2020 18:13:03 GMT   * execute[/srv/2018.stateofthemap.org/Gemfile] action run
Thu, 14 May 2020 18:13:03 GMT     - execute bundle install --deployment
Thu, 14 May 2020 18:15:39 GMT   * execute[/srv/2019.stateofthemap.org/Gemfile] action run
Thu, 14 May 2020 18:15:39 GMT     - execute bundle install --deployment
Thu, 14 May 2020 18:18:14 GMT   * execute[/srv/2020.stateofthemap.org/Gemfile] action run
Thu, 14 May 2020 18:18:14 GMT     - execute bundle install --deployment
```

**Comment by tomhughes** [comment]
I know what you are trying to do ;-)

I'm very reluctant to disturb the ordering though so there's going to need to be a significant gain.

**Comment by mmd-osm** [comment]
Well, the runtime is almost entirely determined by the `stateofthemap` job which takes 29.5 minutes (vs. 30 min total).

For the current repo, I'm seeing some runtimes in the 40-60 minutes range, although this is a bit difficult to say, as long running jobs tend to get aborted by the famous network timeout.

I could imagine 25 minutes total runtime might be achievable, assuming there's some easy to cut down on the runtime of those one or two long running jobs a bit.

**Pull request closed without merging**
