### PR TITLE
RSS feed for .torrent files

### PR DESCRIPTION
**Pull request by mnalis**
As promised in https://github.com/openstreetmap/chef/issues/373, here is RSS feed generator for `.torrent` files.

As requested, it uses `xmlstarlet` to generate valid XML files, and `xmllint` to double-check they are correct before publishing them.

I've tried to simplify feed names while still indicating they are RSS feeds, and what they contain, while still remaining with unique filenames to avoid clashing (on both server and client side). Finalized RSS feeds are to be automatically generated for all torrents, at following static locations:

- https://planet.openstreetmap.org/pbf/planet-pbf-rss.xml
- https://planet.openstreetmap.org/pbf/full-history/history-pbf-rss.xml
- https://planet.openstreetmap.org/planet/planet-bz2-rss.xml
- https://planet.openstreetmap.org/planet/full-history/history-bz2-rss.xml
- https://planet.openstreetmap.org/planet/changesets-bz2-rss.xml
- https://planet.openstreetmap.org/planet/discussions-bz2-rss.xml

RSS feed does not grow indefinitely, but is limited to last 5 entries (keeping more is probably not likely to be useful for sharing)

### CODE REVIEW

**Comment by mnalis** [comment]
If accepted, closes: https://github.com/openstreetmap/chef/issues/373

**Comment by ldeffenb** [comment]
Watching for this to go live so I can update my automatic puller/seeder.

**Comment by mnalis** [comment]
Could someone take a look at this? I've written it in a way as requested, and tested it works. It also contains integrated `xmllint` validations. Of course I'm willing to do any changes if you would like it done differently. It's been 3 months without any comment. 

The failing kitchen test above is for `otrs` machine, completely unrelated to this PR, it that perhaps the problem?

**Comment by mnalis** [comment]
Hi @Firefishy, can you perhaps take a look at this pull request for `.torrent`s too?

It is actually very simple, just a few variable definitions, and two calls to `xmlstarlet` - one to create RSS headers, and one to add a new entry to RSS. But they are broken to dozen lines each for better readability, so patch maybe seems more complex than it is. 

If you have any comments (or further requirements), I'd be glad to oblige!

**Review by Firefishy — APPROVED** [review]

**Review by Firefishy — APPROVED** [review]

**Comment by ldeffenb** [comment]
Hooray!  Now, what might be the URL for the RSS feed?

**Comment by mnalis** [comment]
@ldeffenb the URLs should became **visible when new torrents are published**, so probably on Saturday. The URLs of RSS feeds are listed at the [top of this PR](https://github.com/openstreetmap/chef/pull/383#issue-556266154). I'll also update [the wiki](https://wiki.openstreetmap.org/wiki/Planet.osm#BitTorrent) when that happens. Thanks @Firefishy and everyone involved for making this happen!

**Comment by Firefishy** [comment]
Links are now live (including backfill):
https://planet.openstreetmap.org/pbf/planet-pbf-rss.xml
https://planet.openstreetmap.org/pbf/full-history/history-pbf-rss.xml
https://planet.openstreetmap.org/planet/planet-bz2-rss.xml
https://planet.openstreetmap.org/planet/full-history/history-bz2-rss.xml
https://planet.openstreetmap.org/planet/changesets-bz2-rss.xml
https://planet.openstreetmap.org/planet/discussions-bz2-rss.xml

**Pull request merged**
