### PR TITLE
stateofthemap: Use global bundle caching

### PR DESCRIPTION
**Pull request by Firefishy**
Use global caching of gem bundles, which should speed up tests a lot

### CODE REVIEW

**Comment by tomhughes** [comment]
Is that repo using bundler 2 though? I suspect not given it is still using the `--deployment` switch which I believe is removed in bundler 2.

**Comment by Firefishy** [comment]
Looks like no. I will upgrade the sotm repos shortly.

**Comment by tomhughes** [comment]
Once you do that you will need to merge this - once the repo uses bundler 2 chef will to as well.

**Comment by tomhughes** [comment]
I'd like to understand more about what the option does though - presumably it's not really global because permissions would make that impossible so presumably it is per-user? Is there documentation somewhere?

**Comment by tomhughes** [comment]
Oh that bundle is being installed as root anyway.

**Comment by tomhughes** [comment]
Just give up, it's clearly not worth it if your global cache is now not global at all and you've had to abandon our standardised structure of `/srv` to get there!

**Comment by Firefishy** [comment]
Giving up (for now)... There is some weird gem / bundler action happening.

**Pull request closed without merging**
