### PR TITLE
Added #osm-ua channel

### PR DESCRIPTION
**Pull request by Edward17**
Would be good to add #osm-ua channel to the http://irc.openstreetmap.org/ page.

### CODE REVIEW

**Comment by Edward17** [comment]
@tomhughes Please merge this pull request!

**Comment by matkoniecz** [comment]
@Edward17 Maybe wait a bit longer than 20 minutes?

**Comment by Edward17** [comment]
@matkoniecz Yes, of course.

**Comment by Edward17** [comment]
Thanks!

**Pull request merged**
