### PR TITLE
Add email for MWG osmf-talk owner queue

### PR DESCRIPTION
**Pull request by pnorman**
The OTRS side is set up

### CODE REVIEW

**Comment by tomhughes** [comment]
Sorry what's this for exactly?

**Comment by pnorman** [comment]
It's to let OTRS pick up from the email osmf-talk-owner@otrs.openstreetmap.org, which will go into its own dedicated queue. We'll then switch over the email in mailman, so instead of mailing list stuff ending in the general MWG queue, it'll have its own queue that it automatically goes into.

**Comment by tomhughes** [comment]
Blimey, how much email does osmt-talk-owner get that's it worth all this trouble?

**Comment by pnorman** [comment]
For form submissions we can sort into queues based on the email it comes from, but the only way I know of to get going into the right queue working is with its own email

**Pull request merged**
