### PR TITLE
Add a bundler vendor cache

### PR DESCRIPTION
**Pull request by Firefishy**
DO NOT MERGE YET.

### CODE REVIEW

**Comment by tomhughes** [comment]
No. Just no. Never.

Vendor if you want, but don't even think about committing the vendored modules.

**Comment by tomhughes** [comment]
What on earth are you trying to do? The whole point of vendoring is to give each checkout it's own module set - if you want to share it then just use the global modules!

**Comment by Firefishy** [comment]
> What on earth are you trying to do? The whole point of vendoring is to give each checkout it's own module set - if you want to share it then just use the global modules!

The `--deployment` does a few more things than purely vendoring. Capistrano symlinks `vendor/bundler` between releases to improve deployment speed, bundler is able to cope with the shared folder. I am experimenting to see if there is any real benefit.

**Comment by HolgerJeromin** [comment]
> DO NOT MERGE YET.

We could use [draft pull request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) in such a case.

**Comment by mmd-osm** [comment]
Once thing I didn't understand with the stateofthemap jobs is that we don't use Jekyll that is provided by Ubuntu 18.04 out-of-the-box. Probably I'm missing something here.

A lot of time in this step is spent compiling some libsass library in C on a single CPU for each single year.

**Comment by tomhughes** [comment]
Well because we want to make sure we use the version of jekyll specified in the bundle, otherwise we might not get the results the author of the site expected.

**Comment by Firefishy** [comment]
Around 6 minutes is all we'd save. Likely better to find a way to parallelise the operations.

**Pull request closed without merging**
